@echo off
echo Initializing Git repository...
git init

echo Adding all files...
git add .

echo Creating commit...
git commit -m "Fix chart layout and tooltip positioning - stack charts vertically and prevent tooltip overlap"

echo Setting branch to main...
git branch -M main

echo Adding remote repository...
git remote add origin https://github.com/7717CMI/global-new.git

echo Pushing to GitHub...
git push -u origin main

echo.
echo Done! Press any key to exit...
pause
