@echo off
echo Setting up Git configuration...
git config --global user.email "coherentdrive@gmail.com"
git config --global user.name "7717CMI"

echo Initializing Git repository...
git init

echo Adding all files...
git add .

echo Creating commit...
git commit -m "Fix chart layout and tooltip positioning - stack charts vertically and prevent tooltip overlap"

echo Setting branch to main...
git branch -M main

echo Adding remote repository...
git remote add origin https://github.com/7717CMI/global-new.git

echo Pushing to GitHub...
echo You will be prompted for your GitHub credentials...
echo NOTE: Use your Personal Access Token as password, not your GitHub password
git push -u origin main

echo.
echo Done! Press any key to exit...
pause
